apiVersion: v1
kind: Service
metadata:
  name: pets-app-service
  namespace: prod  # Add your namespace here
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: pets-app
